apiVersion: v1
kind: Service
metadata:
  name: realityshowweb-service
spec:
  selector:
    app: realityshowweb
  ports:
    - protocol: TCP
      port: 8080
      targetPort: realityweb-port

---

apiVersion: v1
kind: ConfigMap
metadata:
  name: realityshowweb-config-map
data:
  server_port: "8080"
  batching_strategy_batch_size: "10"
  batching_strategy_timeout: "30000"

---

apiVersion: apps/v1
kind: Deployment
metadata:
  name: realityshowweb-deploy
  labels:
    app: realityshowweb-deploy
spec:
  replicas: 1
  selector:
    matchLabels:
      app: realityshowweb
  template:
    metadata:
      labels:
        app: realityshowweb
    spec:
      containers:
        - name: realityshowweb
          image: realityshowweb:0.0.1
          imagePullPolicy: IfNotPresent
          env:
            - name: SERVER_PORT
              valueFrom:
                configMapKeyRef:
                  name: realityshowweb-config-map
                  key: server_port
            - name: BATCHING_STRATEGY_BATCH_SIZE
              valueFrom:
                configMapKeyRef:
                  name: realityshowweb-config-map
                  key: batching_strategy_batch_size
            - name: BATCHING_STRATEGY_TIMEOUT
              valueFrom:
                configMapKeyRef:
                  name: realityshowweb-config-map
                  key: batching_strategy_timeout
            - name: RABBITMQ_VOTES_QUEUE_NAME
              valueFrom:
                configMapKeyRef:
                  name: realityshow-config-map
                  key: rabbitmq_votes_queue_name
            - name: MONGODB_HOST
              valueFrom:
                secretKeyRef:
                  name: realityshow-secret
                  key: mongodb_host
            - name: MONGODB_PORT
              valueFrom:
                secretKeyRef:
                  name: realityshow-secret
                  key: mongodb_port
            - name: MONGODB_DATABASE
              valueFrom:
                secretKeyRef:
                  name: realityshow-secret
                  key: mongodb_database
            - name: RABBITMQ_USERNAME
              valueFrom:
                secretKeyRef:
                  name: realityshow-secret
                  key: rabbitmq_username
            - name: RABBITMQ_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: realityshow-secret
                  key: rabbitmq_password
            - name: RABBITMQ_HOST
              valueFrom:
                secretKeyRef:
                  name: realityshow-secret
                  key: rabbitmq_host
            - name: RABBITMQ_PORT
              valueFrom:
                secretKeyRef:
                  name: realityshow-secret
                  key: rabbitmq_port
          ports:
            - containerPort: 8080
              name: realityweb-port
          resources:
            requests:
              cpu: "300m"
              memory: "256Mi"
            limits:
              cpu: "2000m"
              memory: "2Gi"
