apiVersion: v1
kind: Service
metadata:
  name: realityshowvotes-service
spec:
  selector:
    app: realityshowvotes
  ports:
    - protocol: TCP
      port: 8080
      targetPort: votes-port
---

apiVersion: apps/v1
kind: Deployment
metadata:
  name: realityshowvotes-deploy
  labels:
    app: realityshowvotes-deploy
spec:
  replicas: 1
  selector:
    matchLabels:
      app: realityshowvotes
  template:
    metadata:
      labels:
        app: realityshowvotes
    spec:
      containers:
        - name: realityshowvotes
          image: realityshowvotes:0.0.1
          imagePullPolicy: IfNotPresent
          env:
            - name: RABBITMQ_VOTES_QUEUE_NAME
              valueFrom:
                configMapKeyRef:
                  name: realityshow-config-map
                  key: rabbitmq_votes_queue_name
            - name: MONGODB_HOST
              valueFrom:
                secretKeyRef:
                  name: realityshow-secret
                  key: mongodb_host
            - name: MONGODB_PORT
              valueFrom:
                secretKeyRef:
                  name: realityshow-secret
                  key: mongodb_port
            - name: MONGODB_DATABASE
              valueFrom:
                secretKeyRef:
                  name: realityshow-secret
                  key: mongodb_database
            - name: RABBITMQ_USERNAME
              valueFrom:
                secretKeyRef:
                  name: realityshow-secret
                  key: rabbitmq_username
            - name: RABBITMQ_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: realityshow-secret
                  key: rabbitmq_password
            - name: RABBITMQ_HOST
              valueFrom:
                secretKeyRef:
                  name: realityshow-secret
                  key: rabbitmq_host
            - name: RABBITMQ_PORT
              valueFrom:
                secretKeyRef:
                  name: realityshow-secret
                  key: rabbitmq_port
          ports:
            - name: votes-port
              containerPort: 8080
